/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocationsIndexRouteImport } from './routes/locations/index'
import { Route as LocationsCreateRouteImport } from './routes/locations/create'
import { Route as LocationsNameRouteImport } from './routes/locations/$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsCreateRoute = LocationsCreateRouteImport.update({
  id: '/locations/create',
  path: '/locations/create',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsNameRoute = LocationsNameRouteImport.update({
  id: '/locations/$name',
  path: '/locations/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/locations/$name': typeof LocationsNameRoute
  '/locations/create': typeof LocationsCreateRoute
  '/locations/': typeof LocationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/locations/$name': typeof LocationsNameRoute
  '/locations/create': typeof LocationsCreateRoute
  '/locations': typeof LocationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/locations/$name': typeof LocationsNameRoute
  '/locations/create': typeof LocationsCreateRoute
  '/locations/': typeof LocationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/locations/$name' | '/locations/create' | '/locations/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/locations/$name' | '/locations/create' | '/locations'
  id:
    | '__root__'
    | '/'
    | '/locations/$name'
    | '/locations/create'
    | '/locations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocationsNameRoute: typeof LocationsNameRoute
  LocationsCreateRoute: typeof LocationsCreateRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/create': {
      id: '/locations/create'
      path: '/locations/create'
      fullPath: '/locations/create'
      preLoaderRoute: typeof LocationsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$name': {
      id: '/locations/$name'
      path: '/locations/$name'
      fullPath: '/locations/$name'
      preLoaderRoute: typeof LocationsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocationsNameRoute: LocationsNameRoute,
  LocationsCreateRoute: LocationsCreateRoute,
  LocationsIndexRoute: LocationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
